### ISSUE TITLE
Unknown pragma when compiling with MSYS MinGW

### ISSUE THREAD

**Issue by asmaloney** [d-bahr/CRCpp#19]
```
C:/.../CRC.h:896: error: ignoring '#pragma warning ' [-Werror=unknown-pragmas]
  896 | #   pragma warning (disable : 4333)
      |
```

Using "MinGW 13.2.0" from MSYS (`C:/msys64/ucrt64/bin/g++.exe`).

I guess one  (or more) of these is defined when using MSYS:

```cpp
#if defined(WIN32) || defined(_WIN32) || defined(WINCE)
```

Maybe it should be checking for MSVC explicitly instead?

**Comment by d-bahr** [comment]
Thanks for reporting -- I'll take a look.

**Comment by d-bahr** [comment]
Confirmed the fix works with MinGW 13.2.0 from MSYS2 version 20240113.
